import { AppShell } from '@/components/layout/AppShell'
import { ButtonLink } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'

export default function HelpScreen() {
  return <AppShell><div className="page narrow"><h1 className="type-h2">Help, scope & data limitations</h1><Card className="stack p-6">
    <h2 className="type-h3">Limited tester beta — not confidential-client use</h2><p>Only public, synthetic or fully anonymized English Indian legal documents are permitted. Remove names, identifying facts, document metadata and embedded content. Do not upload confidential client, company or sensitive personal data. We do not promise blanket confidentiality or production security.</p>
    <h2 className="type-h3">Where data goes</h2><p>Hosted mode uses Supabase for authentication, database and private file storage, Render for API processing and Vercel for the frontend. Detected reference and quotation text may be sent to the configured legal-source provider (Indian Kanoon). Source lookup may be unavailable when not configured, out of credit or unreachable. Ask the beta administrator which providers and regions are configured before submitting any document.</p>
    <h2 className="type-h3">Retention and deletion</h2><p>Documents default to 7-day retention; the actual expiry appears in Documents. Delete controls remove the application record, file, findings and report snapshots. Physical cleanup can be delayed while free compute is asleep. Hosting backups and provider logs can have separate retention; do not assume deletion removes every provider-held copy. Downloaded reports are your responsibility.</p>
    <h2 className="type-h3">What analysis does and does not do</h2><p>Pattern-based detection locates some case citations, statutory references and quotations. It can miss references and cannot establish comprehensive proposition support, statutory applicability, precedent treatment or legal correctness. “Not found” is not “fabricated”; “source found” is not “verified”. Machine results and saved human decisions are distinct.</p>
    <h2 className="type-h3">Supported inputs and workflow</h2><p>Upload text-based PDF, DOCX or UTF-8 TXT, or paste text. The upload screen shows server-configured limits (normally 10 MB, 50 pages and 200,000 characters). Scanned/image-only PDFs, encrypted PDFs, OCR and non-English workflows are not supported. Review extracted text beside source passages, record your decision and save a report snapshot. Proposed corrections do not modify the original document. Print / save PDF uses your browser print dialog.</p>
    <h2 className="type-h3">Accounts and operations</h2><p>Create an email/password account or sign in to use hosted mode. There are no teams, public sharing or senior review. Use the sign-in form for account access; contact your administrator if email confirmation or recovery is not arriving. Local mode has no login or per-user isolation and must never be exposed publicly. Hosted mode requires Supabase authentication.</p><p>The free API can take about a minute to wake. Jobs and deletion cleanup may pause while it sleeps. Cancel/retry controls show real server status. If upload is interrupted, check Documents before resubmitting and delete incomplete entries. No fabricated progress or evidence is substituted.</p>
    <h2 className="type-h3">Source attribution</h2><p>When Indian Kanoon evidence is available, its official, unaltered “powered by IKanoon” logo appears above the results in reviews and saved reports. The logo loads from Indian Kanoon without a referrer; it is not requested when no Indian Kanoon results are present. Source-link activity records opening a link, not reading or agreement. Always inspect the actual linked judgment and its context.</p>
    <ButtonLink to="/documents">Go to documents</ButtonLink>
  </Card></div></AppShell>
}
