import { useEffect, useRef, useState } from 'react'
import { Button } from '@/components/ui/Button'
import { useAuth } from '@/lib/auth'
import { useDocument } from '@/lib/documents'
import { errorMessage, type AiExplanation, type Finding } from '@/lib/api'

export function AiExplanationContent({ explanation }: { explanation: AiExplanation }) {
  return <div className="stack">
    <h3 className="font-semibold">AI explanation <span className="text-small text-slate">· Unverified</span></h3>
    {explanation.status === 'completed' && <p className="text-small whitespace-pre-wrap break-words">{explanation.text}</p>}
    {explanation.status === 'failed' && <p role="alert" className="notice error">{explanation.error}</p>}
    {explanation.status === 'processing' && <p className="text-small">Generation was pending. No completed explanation is available.</p>}
    <p className="text-small text-slate">Generated by {explanation.model} from the reference alone, not verified source text. May be inaccurate or outdated; check the original authority. Not legal advice or a verification result.</p>
  </div>
}

export function AiExplanationPanel({ finding }: { finding: Finding }) {
  const { api, config } = useAuth()
  const { doc, updateFinding, reload } = useDocument()
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const pending = useRef<AbortController | null>(null)
  useEffect(() => () => pending.current?.abort(), [])
  const explanation = finding.ai_explanation
  const processing = explanation?.status === 'processing' && explanation.started_at * 1000 + 120000 > Date.now()
  async function explain() {
    if (pending.current || busy || processing) return
    const controller = new AbortController()
    pending.current = controller
    setBusy(true); setError('')
    try {
      const saved = await api<Finding>(`/v1/documents/${doc.id}/findings/${finding.id}/explanation`, {
        method: 'POST', signal: controller.signal,
        body: JSON.stringify({ consent: true, request_key: crypto.randomUUID() }),
      })
      if (!controller.signal.aborted) updateFinding(saved)
    } catch (cause) {
      if (!controller.signal.aborted) { setError(errorMessage(cause)); reload() }
    } finally {
      if (!controller.signal.aborted) { pending.current = null; setBusy(false) }
    }
  }
  return <section aria-label="AI reference explanation" className="stack rounded border border-mist bg-paper p-4">
    {explanation && !processing
      ? <AiExplanationContent explanation={explanation} />
      : <h3 className="font-semibold">AI explanation <span className="text-small text-slate">· Unverified</span></h3>}
    {explanation?.status !== 'completed' && <>
      <p className="text-small text-slate">Clicking sends only this detected reference to Google Gemini, not the surrounding document, for a brief general explanation (up to 80 words). Not verified source evidence.</p>
      {!config?.ai_summary_configured && <p className="notice text-small">Gemini is not configured. Enable it on the backend and refresh this page.</p>}
      <Button size="sm" variant="secondary" disabled={busy || processing || !config?.ai_summary_configured || (explanation?.attempts ?? 0) >= 2} onClick={() => void explain()}>
        {busy || processing ? 'Explaining…' : explanation ? 'Retry AI explanation' : 'Explain with AI'}
      </Button>
      {(busy || processing) && <p role="status" className="text-small">Generating a concise explanation… This can take up to a minute.</p>}
      {!busy && !processing && (explanation?.attempts ?? 0) >= 2 && <p className="notice text-small">Two attempts have been used for this reference. No further API calls will be made.</p>}
      <p className="text-small text-slate">Uses the shared Gemini daily limit and budget. Saved explanations are reused without another API call.</p>
    </>}
    {error && <p role="alert" className="notice error">{error}</p>}
  </section>
}
